name = "App-ansicolumn"
readme_from = "script/ansicolumn"
badges = ['github-actions/test', 'metacpan']
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "master"

[FileGatherer]
exclude_match = ['^images/.*']

[unsupported]
os = [
    "MSWin32",
]

