#!/usr/bin/env perl

use v5.14;
use warnings;

use App::ansicolumn;

App::ansicolumn->new->run(@ARGV);

__END__

=encoding utf-8

=head1 NAME

ansicolumn - ANSI terminal sequence aware column command

=head1 SYNOPSIS

ansicolumn [-tx] [-c columns] [-s sep] [file ...]

=head1 DESCRIPTION

From L<column(1)>:

=over 4

The column utility formats its input into multiple columns.  Rows are
filled before columns.  Input is taken from file operands, or, by
default, from the standard input.  Empty lines are ignored.

=over 7

=item B<-c> #

Output is formatted for a display columns wide.

=item B<-s> #

Specify a set of characters to be used to delimit columns for the
-t option.

=item B<-t>

Determine the number of columns the input contains and create a
table.  Columns are delimited with whitespace, by default, or
with the characters supplied using the -s option.  Useful for
pretty-printing displays.

=item B<-x>

Fill columns before filling rows.

=back

=back

B<ansicolumn> is a clone which can handle ANSI terminal sequences.

Some addtional options are available.

=over 4

=over 7

=item B<--column> #

Long name for B<-c>.

=item B<--separator>

Long name for B<-s>.

=item B<--table>

Long name for B<-t>.

=item B<--transpose>, B<--xpose>

Long name for B<-x>.

=item B<--tab> #

Specify tab width.

=item B<--pane> #

Output is formatted in specified number of panes.

=item B<--join> #

When used B<--table> or B<-t> option, each columns are joind by two
space characters (' ') by defualt.  This option will change it.

=item B<--[no-]ignore-space>, B<--[no-]is>

When used B<-t> option, leading spaces are ignored by default.  Use
B<--no-ignore-space> option to disable it.

=back

=back

=head1 INSTALL

=head2 CPANMINUS

    $ cpanm App::Greple
    or
    $ curl -sL http://cpanmin.us | perl - App::Greple

=head1 SEE ALSO

L<column(1)>

L<App::ansicolumn>,
L<https://github.com/kaz-utashiro/App-ansicolumn>

L<Text::ANSI::Printf>,
L<https://github.com/kaz-utashiro/Text-ANSI-Printf>

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright 2020 Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
